openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: Contracts of API
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:52287/api
paths:
  /residences:
    get:
      summary: Get all residences
      description: get all residences
      operationId: get all residences
      responses:
        '200':
          description: Successful operation
          content:
           application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Residence'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
components:
  schemas:
    Residence:
      required:
        - Name
        - ResidenceName
        - Resident
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        Name:
          type: string
          example: 224-A
        ResidenceName:
          type: string
          example: Casa de los Juarez
        Resident:
          type: string
          description: pet status in the store
          example: Alan Palomito
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string