openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: Contracts of API
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:52287/api
paths:
  /auth:
    post:
      summary: Validate user Token
      description: PUT with all fields required to validate user's token
      responses:
        '200':
          description: Token validated successfully
        '400':
          description: Token no longer valid
        '405':
          description: Token Validation exception
        '500':
          description: Internal error, contact support on http://support.aarp.com
components:
  schemas:
    ValidateToken:
      required:
        - TokenId
      type: object
      properties:
        grant_type:
          type: string
          example: authorization_code
        code:
          type: string
          example: RsT5OjbzRn430zqMLgV3Ia
        redirect_uri:
          type: string
          example: https://localhost
        client_id:
          type: string
          example: 507f1f77bcf86cd799439011
        client_secret:
          type: string
          example: 53geej95rk20660
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        access_token:
          type: string
        expiresIn:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string